### ISSUE TITLE
Do i find a bug in the code?

### ISSUE THREAD

**Issue by spx1997** [YuliangXiu/PoseFlow#10]
firstly, thank you for your fantastic project, and i learning a lot from you task.
I read your code seriously, and i thank there have a bug in your code.
I think `ret = fd.write("%d %d %d %d %f \n"%(kp1[m_n[0].queryIdx].pt[0], kp1[m_n[0].queryIdx].pt[**_0_**], kp2[m_n[0].trainIdx].pt[0], kp2[m_n[0].trainIdx].pt[1], m_n[0].distance))` in matching.py should be corrected to`ret = fd.write("%d %d %d %d %f \n"%(kp1[m_n[0].queryIdx].pt[0], kp1[m_n[0].queryIdx].pt[**_1_**], kp2[m_n[0].trainIdx].pt[0], kp2[m_n[0].trainIdx].pt[1], m_n[0].distance))`.
"Yuan Fang", how do you see?

**Comment by YuliangXiu** [comment]
Thanks so much, you are right, can you pull a new request to correct this bug?

**Comment by YuliangXiu** [comment]
bug has been repaired
