### ISSUE TITLE
about the prediction

### ISSUE THREAD

**Issue by KaaiLee** [YuliangXiu/PoseFlow#13]
我有一些相关问题想请教一下,第一.我用alphapose-pytorch在我自己的数据上生成的关键点数据能否直接拿过来做姿态追踪的预测(我的数据是没有做标签,只是想做一下预测看一下算法的泛化性能)?如果是可行的话,那代码中的标签数据该怎么样设置呢?

**Comment by YuliangXiu** [comment]
刚刚我更新了一个[PoseFlow(general version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version)，现在你可以直接用alphapose在你的数据集上生成关键点数据，然后一行代码就可以完成姿态追踪的预测及可视化。
