### ISSUE TITLE
How to use tracker.py on a video?

### ISSUE THREAD

**Issue by RuWang15** [YuliangXiu/PoseFlow#14]
I already get the pose estimations of a video by AlphaPose according to the QuickStart. But I don't know how can I use tracker.py to get track ID with a JSON file and a video. Should I convert the video to images first?

**Comment by RuWang15** [comment]
I already solved the problem. Thanks for your code! I think you might want to provide a instruction on how to use the code and what the variables mean (for those who are not familiar with the file structure of PoseTrack like me). I would say there's too much to change in tracker.py to fit into my project. But thanks anyway!

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)] has already released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.

**Comment by sharmaabhishekk** [comment]
> I already solved the problem. Thanks for your code! By the way, I think you might want to provide a instruction on how to use the code and what the variables mean (for those who are not familiar with the file structure of PoseTrack like me). I would say there's too much to change in tracker.py to fit into my project. But thanks anyway!

I'm facing a similar issue. I have a video input and I already have AlphaPose working on it (i.e. have the `alphapose-results.json` file). I also want to run PoseFlow on it to get the IDs for the detected individuals and other keypoints. Could you tell me how you figured this out?
