### ISSUE TITLE
Running Time Very Slow

### ISSUE THREAD

**Issue by lijiaman** [YuliangXiu/PoseFlow#15]
Hi, 

I tried your codes, for a 4min video (24fps), after I got results from alphapose, when I ran the poseflow, it's extremely slow. Even the time of loading alphapose is long, about 3mins. And the total tracking time is at least 2 hours... I wonder why this happens. You said the running time is 24fps for orb version. Please help. thanks a lot!

**Comment by YuliangXiu** [comment]
how many people in your video?

**Comment by lijiaman** [comment]
Thanks for your quick response. I tried video like this https://www.youtube.com/watch?v=aIu-ohNdbcg . I also tried to reduce the number of people per frame to 5(basically only keep top5 large boxes per frame), it's still slow.

**Comment by lijiaman** [comment]
The reported 24fps is for how many people?

**Comment by lijiaman** [comment]
Hi, I checked your codes for tracker-general and tracker-baseline, it seems they both calculate the matching one by one, not batching. How could do batch processing for matching? And does 24fps count the calculation time of matching?

**Comment by YuliangXiu** [comment]
CPU: Intel® Core™ i9-7900X CPU @ 3.30GHz × 20 
Memory: 125.6 GiB

Here is my system setting, what is yours?

**Comment by lijiaman** [comment]
Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz

I think maybe it's also related to image resolution? what image size are you using? did you resize the images?

**Comment by YuliangXiu** [comment]
No, I did not resize the images.
Would you mind sharing the video with me? I want to test it on my computer and try to find the problems. You can send me via yuliangxiu at sjtu dot edu dot cn

**Comment by YuliangXiu** [comment]
I have not received that...

**Comment by lijiaman** [comment]
I sent again (with my email ljm@cs.toronto.edu). Please let me know if you
received it. Thanks!

**Comment by YuliangXiu** [comment]
solved by emails

**Comment by evandesantola** [comment]
I am encountering a similar issue with performance.  How was this resolved?

**Comment by YuliangXiu** [comment]
If your video is too long, which contains thousands of frames, the speed will slow down due to the json data structure IO bottleneck.

**Comment by priya-dwivedi** [comment]
@YuliangXiu : I am also encountering speed issues. I have a 500 frame video with 4-5 people per frame. How do I resolve the json data structure bottleneck?

**Comment by Ayendra** [comment]
@YuliangXiu  
I want to intergrate poseflow with an real-time applications (such as webcam-demo). Any leads?

**Comment by MagnusAnders** [comment]
How can I run this on GPU ? I have a video of app. 1500 frames and 4 poeple and it takes about 1h to track...

**Comment by fshemaj** [comment]
Hi, also interested in finding out how to speed up this process. Taking too long for me as well
