### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by lxy5513** [YuliangXiu/PoseFlow#16]
你好，非常感谢你的代码的开源。我跑了一视频文件，发现关键点在pose-flow处理的坐标位置没有变化，我想请教一下如下问题  
<br> 
假定AlphaPose生成了一系列关键点json文件。
待解决问题：
1. Alpha Pose 生成的 json文件中每一帧的每个人只会有一个边框， 一套相应的关键点？  
  
2. Pose Flow 处理json 文件
> 追踪匹配每个人在视频中连续性  
是否调节了human bbox    
是否调节了keypoints的位置

**Comment by YuliangXiu** [comment]
1. 对的，每一帧每一个人只有一个box，一套pose
2. 开源的这个版本中，没有调节box和pose

**Comment by lxy5513** [comment]
好的，谢谢你快速的回复。
