### ISSUE TITLE
有一个幼稚的问题想要请教

### ISSUE THREAD

**Issue by 1icas** [YuliangXiu/PoseFlow#2]
你好，这两天拜读了你的这篇论文并看了你的代码。但有一个很简单的问题一直没有相通。希望能帮忙解答一下。不胜感激。
  在 readme 的 Quick Start部分，首先需要运行alpha pose来生成一个video的每帧的human keypoint，然后运行 track.py。这里我一直没想明白。
  alpha pose已经把每帧的human keypoint预测出来了。那么为什么还需要 track呢？直接把每帧预测出来的human keypoint绘制到屏幕上去，不就已经可以了吗

**Comment by YuliangXiu** [comment]
@1icas 这个项目解决的问题，是跟踪人体关键点，而不是可视化人体关键点，因为视频基本都是多人的，所以需要用跟踪算法来判断这一帧的A 到了下一帧跑到什么地方。
