### ISSUE TITLE
Action recognition on own video

### ISSUE THREAD

**Issue by sophia-wright-blue** [YuliangXiu/PoseFlow#6]
Hello,

 Thank your for releasing the code for your paper. I'd like to be able to obtain action recognition results on my own video that contains a group of people walking around. Can you point me to any repos that use the results of this PoseFlow code to produce action recognition classification results?

Thank you,

**Comment by YuliangXiu** [comment]
As far as I know, there is no repo using PoseFlow to do action recognition. But pose information can be used to boost action recognition tasks, you can try to google "pose based attention action recognition" or something like that.

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.

**Comment by sophia-wright-blue** [comment]
thank you for that information @YuliangXiu , i'm going to take some time out to look into this,
