### ISSUE TITLE
关于结果的请教

### ISSUE THREAD

**Issue by my-hello-world** [YuliangXiu/PoseFlow#7]
想问下您，我得到了结果的.json 文件，我怎么看或者保存的追踪过的结果图片呢？
还有就是能根据 alphapose处理的视频结果+poseflow 得到追踪的视频结果吗

**Comment by YuliangXiu** [comment]
我没有单独写PoseFlow 的可视化，不过你可以稍微改动一下[AlphaPose/json-video.py](https://github.com/MVIG-SJTU/AlphaPose/blob/master/predict/json/json-video.py)来做可视化

对的，需要先用AlphaPose 得到每一帧的pose 结果，然后用poseflow 去做tracking
