### ISSUE TITLE
How to evaluate posetrack dataset with `tracker.py`?

### ISSUE THREAD

**Issue by SeanSyue** [YuliangXiu/PoseFlow#8]
@YuliangXiu I want to evaluate pose track performance on **posetrack-val2018** dataset and I've read [your reply in this issue](https://github.com/YuliangXiu/PoseFlow/issues/4#issuecomment-426147053), where you just mentioned:

> you can obtain the pose_coordinates from trainset and validset of PoseTrack dataset(json or mat files in posetrack_data/annotations). Otherwise, you need to generate pose_coordinates via Multi-Person Pose Estimation Framework, such as AlphaPose.

If I was right, then evaluating on `posetrack dataset` **no need to do pose estimation beforehead?**
Then I found [this line in 'tracker.py'](https://github.com/YuliangXiu/PoseFlow/blob/master/tracker.py#L66). Seems that it is a result json file generated by `AlphaPose`. 
### So here is my question:
1. **`tracker.py` is a general solution for unlabeled data?** and
2. If I want to evaluate the origin **posetrack dataset**, I need to **modify `tracker.py`?**

**Comment by YuliangXiu** [comment]
1. yes, it's a general solution for any multi-person image
2. no, but if you want to test on some new dataset, you need to modify it

**Comment by SeanSyue** [comment]
@YuliangXiu OK, I understand. So if I want to evaluate `posetrack-2018` dataset, which value should I assign in [this line in `tracker.py`](https://github.com/YuliangXiu/PoseFlow/blob/master/tracker.py#L66)?

**Comment by YuliangXiu** [comment]
this file was generated from AlphaPose, you need to do pose estimation on dataset and then do pose tracking on the estimated results. You need to read the README.md carefully.

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.
