### ISSUE TITLE
three question about poseflow

### ISSUE THREAD

**Issue by Lywzz** [YuliangXiu/PoseFlow#9]
hello, i have read the code and paper and i have three questions.
1.Can i use poseflow after alphapose of pytorch branch?
2.In your poseflow code, what is the drop threshold mean，it defaults to 2 and how to take the value？
3.I find that poseflow relies heavily on the results of alphapose，if alphapose does not detect keypoints in a frame, the result of tracking may be wrong.So do you have some ideas for correcting the keypoints of bigger error？
Please have a look，thank you

**Comment by YuliangXiu** [comment]
1. Yes, but you need to change the alphapose json result file according to the Poseflow input format showed in my Readme.
2. drop threshold mean filter all the keypoints with low score.
3. you can refer to my paper, I put forward several methods(like PF-NMS) to correct alphapose keypoints error

**Comment by Lywzz** [comment]
thank you, but i can't find PF-NMS in your code

**Comment by YuliangXiu** [comment]
[PoseFlow(General Version)](https://github.com/YuliangXiu/PoseFlow#for-any-datasets-general-version) has already been released, now you can do pose tracking on any private dataset, the new version also supports pose tracking results visualization.
